### ISSUE TITLE
Error en el código de registrar cliente en el guardado a la base de datos

### ISSUE THREAD

**Issue by U23250923** [yederlv/Grupo05-Curso-Integrador-I#10]
![Error en el codigo de registro de cliente](https://github.com/yederlv/Grupo05-Curso-Integrador-I/assets/169417197/7d4e93c2-20e6-4e8c-8773-25d8bd046b13)

**Comment by yederlv** [comment]
Dado que tu clase MascotaDAO no tiene métodos estáticos, necesitas crear una instancia de MascotaDAO para poder llamar al método addMascota.
`ClienteDAO clienteDAO = new ClienteDAO(); `
`clienteDAO.addCliente(cliente);`
